import Link from 'next/link';
import { notFound } from 'next/navigation';
import { readKnowledgePackage } from '@/lib/knowledge-engine/read-packages';

export default async function KnowledgePackagePage({ params, searchParams }: { params: { slug: string }; searchParams: { imported?: string } }) {
  const packageData = await readKnowledgePackage(params.slug).catch(() => null);
  if (!packageData) notFound();
  const chapters = new Map(packageData.chapters.map((chapter) => [chapter.chapterId, chapter]));
  return <div className="space-y-6">{searchParams.imported === '1' && <div className="rounded-2xl bg-emerald-50 p-4 text-emerald-900">Knowledge package imported successfully: {packageData.totalParts} parts and {packageData.totalChapters} chapters detected.</div>}<section className="rounded-3xl border border-emerald-100 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-emerald-700">{packageData.documentId} · v{packageData.version}</p><h1 className="mt-2 text-3xl font-bold">{packageData.title}</h1><p className="mt-2 text-sm text-slate-500">Source: {packageData.sourceFileName}</p></div><span className="rounded-full bg-emerald-50 px-4 py-2 text-sm font-semibold text-emerald-800">{packageData.status}</span></div><div className="mt-5 flex flex-wrap gap-4 text-sm text-slate-600"><span>{packageData.totalParts} parts</span><span>{packageData.totalChapters} chapters</span><span>{packageData.totalWordCount.toLocaleString()} words</span></div><div className="mt-5 flex flex-wrap gap-3"><Link href={`/knowledge/packages/${encodeURIComponent(packageData.slug)}/export`} className="rounded-full border border-emerald-200 px-4 py-2 text-sm font-semibold text-emerald-900">Open full export</Link><Link href="/knowledge/packages" className="rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700">All packages</Link></div></section><section className={`rounded-2xl p-5 ${packageData.validation.valid ? 'bg-emerald-50 text-emerald-900' : 'bg-red-50 text-red-800'}`}><h2 className="font-bold">Validation {packageData.validation.valid ? 'passed' : 'failed'}</h2>{packageData.validation.errors.length > 0 && <List values={packageData.validation.errors} />}{packageData.validation.warnings.length > 0 && <><h3 className="mt-4 font-semibold">Warnings</h3><List values={packageData.validation.warnings} /></>}</section><div className="space-y-5">{packageData.parts.map((part) => <section key={part.partId} className="rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-emerald-700">{part.partId}</p><h2 className="mt-1 text-xl font-bold">{part.title}</h2><div className="mt-4 grid gap-3">{part.chapterIds.map((chapterId) => { const chapter = chapters.get(chapterId); return chapter ? <Link key={chapterId} href={`/knowledge/packages/${encodeURIComponent(packageData.slug)}/chapters/${encodeURIComponent(chapterId)}`} className="rounded-xl bg-slate-50 p-4 hover:bg-emerald-50"><p className="font-semibold">Chapter {chapter.chapterNumber}: {chapter.title}</p><p className="mt-1 text-sm text-slate-500">{chapter.wordCount.toLocaleString()} words · {chapter.headingCount} headings</p></Link> : null; })}</div></section>)}</div></div>;
}

function List({ values }: { values: string[] }) { return <ul className="mt-2 list-disc space-y-1 pl-5 text-sm">{values.map((value) => <li key={value}>{value}</li>)}</ul>; }
