import { importKnowledgeAction } from '@/app/actions';
import { isReadOnlyMode, readOnlyMessage } from '@/lib/hwos';

export default function KnowledgeImportPage({ searchParams }: { searchParams: { error?: string } }) {
  return <div className="mx-auto max-w-4xl space-y-6"><div><h1 className="text-3xl font-bold">Import canonical knowledge</h1><p className="mt-2 text-slate-600">Parse a canonical Markdown document into a versioned, immutable multi-chapter knowledge package. Content is preserved; no AI processing occurs.</p></div>{searchParams.error && <div className="rounded-2xl bg-red-50 p-4 text-red-800">{searchParams.error}</div>}{isReadOnlyMode && <div className="rounded-2xl bg-amber-50 p-4 text-amber-900">{readOnlyMessage}</div>}<form action={isReadOnlyMode ? undefined : importKnowledgeAction} className="space-y-5 rounded-3xl border border-emerald-100 bg-white p-6 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><Field name="title" label="Document title" placeholder="Healthcare Patient Psychology" disabled={isReadOnlyMode} /><Field name="documentId" label="Document ID" placeholder="K-01" disabled={isReadOnlyMode} /><Field name="slug" label="Slug" placeholder="01-healthcare-patient-psychology" disabled={isReadOnlyMode} /><Field name="version" label="Version" placeholder="2.0" disabled={isReadOnlyMode} /><Field name="status" label="Status" placeholder="Frozen" disabled={isReadOnlyMode} /><Field name="sourceFileName" label="Source file name" placeholder="01 Healthcare Patient Psychology - MASTER (Frozen v2.0).md" disabled={isReadOnlyMode} /><Field name="expectedParts" label="Expected Parts (optional)" placeholder="7" disabled={isReadOnlyMode} required={false} type="number" /><Field name="expectedChapters" label="Expected Chapters (optional)" placeholder="26" disabled={isReadOnlyMode} required={false} type="number" /></div><label className="block"><span className="font-semibold">Markdown content</span><textarea name="rawMarkdown" required disabled={isReadOnlyMode} className="mt-2 min-h-[420px] w-full rounded-2xl border border-emerald-100 p-4 font-mono text-sm leading-6 outline-none focus:border-emerald-400 disabled:bg-slate-100" placeholder="# PART I — Foundations&#10;&#10;# Chapter 1 — Purpose&#10;&#10;Paste the complete canonical Markdown document here." /></label><button disabled={isReadOnlyMode} className="rounded-full bg-emerald-700 px-6 py-3 font-semibold text-white disabled:cursor-not-allowed disabled:bg-slate-400">Import Knowledge</button></form></div>;
}

function Field({ name, label, placeholder, disabled, required = true, type = 'text' }: { name: string; label: string; placeholder: string; disabled: boolean; required?: boolean; type?: string }) {
  return <label><span className="font-semibold">{label}</span><input name={name} type={type} min={type === 'number' ? 1 : undefined} required={required} disabled={disabled} className="mt-2 w-full rounded-xl border border-emerald-100 p-3 outline-none focus:border-emerald-400 disabled:bg-slate-100" placeholder={placeholder} /></label>;
}
