import Link from 'next/link';
import { loadAgentRegistry } from '@/lib/registry';
import { validateRegistries } from '@/lib/validation';

export default async function AgentRegistryPage() {
  const [registry, validation] = await Promise.all([loadAgentRegistry(), validateRegistries()]);
  const agents = [...registry.agents].sort((a, b) => a.executionOrder - b.executionOrder);
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-700">Registry v{registry.version}</p><h1 className="mt-2 text-3xl font-bold">Agent registry</h1><p className="mt-2 text-slate-600">Declarative research roles and dependencies. No agents execute in v0.1.</p></div><Link href="/context-preview" className="rounded-full bg-emerald-700 px-5 py-2 font-semibold text-white">Preview context</Link></div>{!validation.valid && <div className="rounded-2xl bg-red-50 p-5 text-red-800"><p className="font-bold">Registry validation errors</p><ul className="mt-2 list-disc pl-5">{validation.errors.map((error) => <li key={error}>{error}</li>)}</ul></div>}<div className="grid gap-4">{agents.map((agent) => <article key={agent.id} className="rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-emerald-700">{agent.department} · execution {agent.executionOrder}</p><h2 className="mt-1 text-xl font-bold">{agent.name}</h2><p className="text-sm text-slate-500">{agent.id}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-700">{agent.status}</span></div><p className="mt-3 text-slate-600">{agent.role}</p><dl className="mt-4 grid gap-2 text-sm md:grid-cols-2"><div><dt className="font-semibold">Inputs</dt><dd className="text-slate-600">{agent.inputDeliverables.join(', ') || 'Project files'}</dd></div><div><dt className="font-semibold">Outputs</dt><dd className="text-slate-600">{agent.outputDeliverables.join(', ')}</dd></div><div><dt className="font-semibold">Required knowledge</dt><dd className="text-slate-600">{agent.requiredKnowledge.join(', ')}</dd></div><div><dt className="font-semibold">Downstream</dt><dd className="text-slate-600">{agent.downstreamAgent ?? 'Department handoff'}</dd></div></dl><Link href={`/agents/inspect/${encodeURIComponent(agent.id)}`} className="mt-5 inline-block rounded-full border border-emerald-200 px-4 py-2 text-sm font-semibold text-emerald-900">Open Agent Inspector</Link></article>)}</div></div>;
}
